version: '3.3'
services:
  dbinstance:
    image: mysql
    environment:
      MYSQL_DATABASE: 'db_sample'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '3306:3306'
  app:
    build: .
    command: uvicorn app.main:app --reload --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - dbinstance
  